[package]
name = "zitadel"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.9"
prost-types = "0.9"
tonic = "0.6"
tonic-types = "0.4"
grpc-helper = { version = "1.0.0", path="grpc-helper" }
chrono = "0.4.19"
jsonwebtoken = "8.0.0-beta.8"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tonic-build = "0.6"
